name = "79ratio"
compatibility_date = "2024-09-23"
main = ".open-next/worker.js"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

[assets]
binding = "STATIC_CONTENT"
directory = ".open-next/assets"
run_worker_first = true

[build]
command = "npm run build:cloudflare"
