name = "79-ratio-website-option"
compatibility_date = "2024-09-23"
pages_build_output_dir = ".open-next"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

[build]
command = "npm run build:open-next"
