name = "79ratiocom.helpdesk-bf2.workers.dev"
compatibility_date = "2024-09-23"
main = ".open-next/worker.js"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

[build]
command = "npm run build:cloudflare"
